//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ByValByRefServiceClient.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ByValByRefDemoServiceSoap", Namespace="http://www.timrobinson41tests.com/DemoProject")]
    public partial class ByValByRefDemoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FooOperationCompleted;
        
        private System.Threading.SendOrPostCallback BarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ByValByRefDemoService() {
            this.Url = global::ByValByRefServiceClient.Properties.Settings.Default.ByValByRefServiceClient_localhost_ByValByRefDemoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FooCompletedEventHandler FooCompleted;
        
        /// <remarks/>
        public event BarCompletedEventHandler BarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.timrobinson41tests.com/DemoProject/Foo", RequestNamespace="http://www.timrobinson41tests.com/DemoProject", ResponseNamespace="http://www.timrobinson41tests.com/DemoProject", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("c")]
        public int Foo(int a, ref int b) {
            object[] results = this.Invoke("Foo", new object[] {
                        a,
                        b});
            b = ((int)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void FooAsync(int a, int b) {
            this.FooAsync(a, b, null);
        }
        
        /// <remarks/>
        public void FooAsync(int a, int b, object userState) {
            if ((this.FooOperationCompleted == null)) {
                this.FooOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFooOperationCompleted);
            }
            this.InvokeAsync("Foo", new object[] {
                        a,
                        b}, this.FooOperationCompleted, userState);
        }
        
        private void OnFooOperationCompleted(object arg) {
            if ((this.FooCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FooCompleted(this, new FooCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.timrobinson41tests.com/DemoProject/Bar", RequestNamespace="http://www.timrobinson41tests.com/DemoProject", ResponseNamespace="http://www.timrobinson41tests.com/DemoProject", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("d3")]
        public Demo Bar(Demo d1, ref Demo d2) {
            object[] results = this.Invoke("Bar", new object[] {
                        d1,
                        d2});
            d2 = ((Demo)(results[1]));
            return ((Demo)(results[0]));
        }
        
        /// <remarks/>
        public void BarAsync(Demo d1, Demo d2) {
            this.BarAsync(d1, d2, null);
        }
        
        /// <remarks/>
        public void BarAsync(Demo d1, Demo d2, object userState) {
            if ((this.BarOperationCompleted == null)) {
                this.BarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBarOperationCompleted);
            }
            this.InvokeAsync("Bar", new object[] {
                        d1,
                        d2}, this.BarOperationCompleted, userState);
        }
        
        private void OnBarOperationCompleted(object arg) {
            if ((this.BarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BarCompleted(this, new BarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.timrobinson41tests.com/DemoProject")]
    public partial class Demo {
        
        private int m1Field;
        
        /// <remarks/>
        public int M1 {
            get {
                return this.m1Field;
            }
            set {
                this.m1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FooCompletedEventHandler(object sender, FooCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FooCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FooCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int b {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BarCompletedEventHandler(object sender, BarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Demo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Demo)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Demo d2 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Demo)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591